using System;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UI;

/// <summary>
/// ƒJپ[ƒh‘I‘ً‚ئ–hŒنƒAƒNƒVƒ‡ƒ“‚ج“ü—ح‚ًڈˆ—‌‚·‚éƒRƒ“ƒ|پ[ƒlƒ“ƒg
/// </summary>
public class BattleInputReader : MonoBehaviour, InputControls.IBattleActionActions, InputControls.IDefenseActionActions
{
    //[SerializeField] private Text debugText;
    public event Action<int> CardSelectEvent;
    public event Action DisCardEvent;
    public event Action<int> OnDefend;
    public event Action<int> OnDefendCanceled;

    private InputControls controls;

    private void OnEnable()
    {
        if (controls == null)
        {
            controls = new InputControls();
            controls.BattleAction.SetCallbacks(this);
            controls.DefenseAction.SetCallbacks(this);
        }
        EnableBattleActionMap();
    }

    private void OnDisable()
    {
        controls?.BattleAction.Disable();
        controls?.DefenseAction.Disable();
    }

    /// <summary>
    /// ƒvƒŒƒCƒ„پ[‚جƒJپ[ƒh‘I‘ً“ü—ح‚¾‚¯‚ً‹–‰آ‚·‚é
    /// </summary>
    public void EnableBattleActionMap()
    {
        controls.DefenseAction.Disable();
        controls.BattleAction.Enable();
    }

    /// <summary>
    /// “G‚جچUŒ‚‚ة‘خ‚·‚é–hŒن“ü—ح‚¾‚¯‚ً‹–‰آ‚·‚é
    /// </summary>
    public void EnableDefenseActionMap()
    {
        controls.BattleAction.Disable();
        controls.DefenseAction.Enable();
    }

    /// <summary>
    /// ‘S‚ؤ‚جƒoƒgƒ‹/–hŒن“ü—ح‚ً–³Œّ‚ة‚·‚é
    /// </summary>
    public void DisableAllActionMaps()
    {
        controls?.BattleAction.Disable();
        controls?.DefenseAction.Disable();
    }

    // --- BattleAction (ƒJپ[ƒh‘I‘ً) ---
    public void OnCardSelectOne(InputAction.CallbackContext context)
    {
        if (!context.ReadValueAsButton()) { return; }
        CardSelectEvent?.Invoke(0);
    }

    public void OnCardSelectTwo(InputAction.CallbackContext context)
    {
        if (!context.performed) { return; }
        CardSelectEvent?.Invoke(1);
    }

    public void OnCardSelectTree(InputAction.CallbackContext context)
    {
        if (!context.performed) { return; }
        CardSelectEvent?.Invoke(2);
    }

    public void OnDisCard(InputAction.CallbackContext context)
    {
        if (!context.performed) { return; }
        DisCardEvent?.Invoke();
    }

    /// <summary>
    /// DefenseAction (–hŒن/ƒJƒEƒ“ƒ^پ[)
    /// </summary>
    /// <param name="context"></param>
    public void OnDefenseOne(InputAction.CallbackContext context)
    {
        // ƒLپ[‚ھ‰ں‚³‚ê‚½ڈuٹش‚ة OnDefend ‚ً”­چs
        if (context.performed)
        {
            OnDefend?.Invoke(1);
        }
        // ƒLپ[‚ھ—£‚³‚ê‚½ڈuٹش‚ة OnDefendCanceled ‚ً”­چs
        else if (context.canceled)
        {
            OnDefendCanceled?.Invoke(1);
        }
    }

    public void OnDefenseTwo(InputAction.CallbackContext context)
    {
        if (context.performed)
        {
            OnDefend?.Invoke(2);
        }
        else if (context.canceled)
        {
            OnDefendCanceled?.Invoke(2);
        }
    }

    public void OnDefenseTree(InputAction.CallbackContext context)
    {
        if (context.performed)
        {
            OnDefend?.Invoke(3);
        }
        else if (context.canceled)
        {
            OnDefendCanceled?.Invoke(3);
        }
    }
    public void OnDefenseFour(InputAction.CallbackContext context)
    {
        if (context.performed)
            OnDefend?.Invoke(4);
        else if (context.canceled)
            OnDefendCanceled?.Invoke(4);
    }

}